repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        name: Black
        entry: poetry run black

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

# - repo: local
#   hooks:
#     - id: safety
#       name: Safety
#       entry: poetry run safety check --full-report
#       pass_filenames: false
#       language: system
# - repo: local
#   hooks:
#     - id: mypy
#       name: MyPy
#       entry: poetry run mypy
#       language: system
#       types: ['python']
#       exclude: examples/
# - repo: local
#   hooks:
#     - id: pylint
#       name: Pylint
#       entry: poetry run pylint --jobs=0
#       language: system
#       types: ['python']
# - repo: local
#   hooks:
#     - id: flake8
#       name: Flake8
#       entry: poetry run flake8
#       language: system
#       types: ['python']
# - repo: https://github.com/igorshubovych/markdownlint-cli
#   rev: v0.29.0
#   hooks:
#   - id: markdownlint
