name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important for semantic versioning to work correctly

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Version Bump and Changelog
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        poetry run semantic-release version --verbosity=DEBUG
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API }}
        packages_dir: dist

    - name: Create GitHub Release
      run: poetry run semantic-release publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
