name: Publish Package

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true && github.head_ref == 'dev'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Necessary for tags and history

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install poetry
        poetry install

    - name: Update Version, Changelog, and Commit Changes
      run: |
        chmod +x .github/workflows/update_version_and_changelog.sh
        .github/scripts/update_version_and_changelog.sh
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pyproject.toml __init__.py CHANGELOG.md
        git commit -m "Update version and changelog [skip ci]"
        git tag $(poetry version -s)
        git push origin HEAD:main --tags

    - name: Build and Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API }}
      run: |
        poetry build
        poetry publish

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_VERSION=$(poetry version -s)
        gh release create $TAG_VERSION --notes "Release notes here" -t $TAG_VERSION
